### ISSUE TITLE
Unable to assert an element is available but not click it.

### ISSUE THREAD

**Issue by RichardBoettcher** [lundbird/SimpleGUI#2]
Assert heading "XXX" exist
Assert heading id:123Curve exists
${value}=  Read heading id:123Curve 
Should Be Equal As Strings  ${value}  ${value_to_compare}

Assert dropdown title "YYY" exists with name "ZZZ" (The idea is that the ID maybe the same but the text maybe different based on the supported language that is loaded.
Assert dropdown option "abcd" exists.
Select dropdown option "abcd"

**Comment by lundbird** [comment]
Hey Richard. Thanks for the update! I'll take a look over break.

**Comment by lundbird** [comment]
Richard, I added these methods to the newest release.
bool exists(id,child,timeout)
string getProperty(id,property,child,timeout)
