### ISSUE TITLE
"DLL load failed;" problem with CLR?

### ISSUE THREAD

**Issue by xhevahir** [lundbird/SimpleGUI#3]
I can't load autogui, as the "import clr" statement produces this error message: "DLL load failed: %1 is not a valid Win32 application."

From googling, it seems there might be a 32-bit DLL where there should be a 64-bit?

**Comment by xhevahir** [comment]
So, I've uninstalled my (64-bit) Python2 and installed 32-bit, and now I get the message "Unhandled Exception: System.IO.FileLoadException: could not load file or assembly python.runtime version=4.0.0.1."

**Comment by xhevahir** [comment]
Closed accidentally. Reopening now. (Although maybe it should be a different issue now?)

**Comment by lundbird** [comment]
Autogui works on winform and wpf applications. clr is the pythonnet package which is not working on python >3.6. I am not sure about the second issue. For reference I am using python 64 bit 3.6.1. What are you using this on?

**Comment by xhevahir** [comment]
That must have been my problem--I had tried and failed to make it work on 3.7; now on 3.6 (64-bit), it's working. Thanks!
